### ISSUE TITLE
有人抄你的项目

### ISSUE THREAD

**Issue by Jess-Qiu** [JontyMin/Jonty.Blog#4]
🐶

**Comment by ElderJames** [comment]
显而易见，这个项目是fork自：https://github.com/Meowv/Blog
但是，按照MIT授权协议，需要声明一下原项目的出处、作者和原协议文件。

**Comment by JontyMin** [comment]
> 显而易见，这个项目是fork自：https://github.com/Meowv/Blog
> 但是，按照MIT授权协议，需要声明一下原项目的出处、作者和原协议文件。

是的，本项目是根据星哥的项目做的，之前README有声明原出处😁，已更新上，谢谢提醒
